### import the required libs

In [1]:
import pandas as pd
import numpy as np

### read and explore the data

In [2]:
df = pd.read_csv(r'dirty_cafe_sales.csv')
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 1.1 MB

In [4]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [5]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

#### The column `Transaction ID` is the only completed column which has no null values

### check the cleaning of `Transaction ID` column

In [6]:
df['Transaction ID'].str.match(r'^TXN_\d{7}$').sum()

np.int64(10000)

In [7]:
df['Transaction ID'].unique()

<ArrowStringArray>
['TXN_1961373', 'TXN_4977031', 'TXN_4271903', 'TXN_7034554', 'TXN_3160411',
 'TXN_2602893', 'TXN_4433211', 'TXN_6699534', 'TXN_4717867', 'TXN_2064365',
 ...
 'TXN_1538510', 'TXN_3897619', 'TXN_2739140', 'TXN_4766549', 'TXN_7851634',
 'TXN_7672686', 'TXN_9659401', 'TXN_5255387', 'TXN_7695629', 'TXN_6170729']
Length: 10000, dtype: str

#### The `Transaction ID` column have no duplicated values and the syntax of it is valid

### check the cleaning of `Item` column

In [8]:
df['Item'].unique()

<ArrowStringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

#### all the values have no typo error or extra white spaces but there is some values are `Error`, `Unknown`, and `nan`

In [9]:
df.loc[(df['Item'].isin(['Error','UNKNOWN']))|(df['Item'].isna())]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
30,TXN_1736287,NaN,5,2.0,10.0,Digital Wallet,NaN,2023-06-02
31,TXN_8927252,UNKNOWN,2,1.0,ERROR,Credit Card,ERROR,2023-11-06
33,TXN_7710508,UNKNOWN,5,1.0,5.0,Cash,NaN,ERROR
...,...,...,...,...,...,...,...,...
9876,TXN_3105633,NaN,1,2.0,2.0,NaN,In-store,2023-03-30
9885,TXN_4659954,NaN,3,4.0,12.0,Credit Card,In-store,NaN
9946,TXN_8807600,UNKNOWN,1,4.0,4.0,Cash,Takeaway,2023-09-24
9994,TXN_7851634,UNKNOWN,4,4.0,16.0,NaN,NaN,2023-01-08
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02

##### WILL LEAVE THE `ITEM` COLUMN FOR NOW TO COMPLETE THE DATA FOR OTHER COLUMNS IN ORDER TO HELP US IN FILL THE NA VALUES

### Standardize the columns that have numeric values

In [10]:
df['Quantity'].isna().sum()

np.int64(138)

In [11]:
df.loc[df['Quantity'].isin(['ERROR','UNKNOWN']),'Quantity'] = np.nan

In [12]:
df['Quantity'] = df['Quantity'].astype(float)

In [13]:
df['Price Per Unit'].unique()

<ArrowStringArray>
['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN']
Length: 9, dtype: str

In [14]:
df.loc[df['Price Per Unit'].isin(['ERROR','UNKNOWN']),'Price Per Unit'] = np.nan

In [15]:
df['Price Per Unit'] = df['Price Per Unit'].astype(float)

In [16]:
df['Total Spent'].unique()

<ArrowStringArray>
[    '4.0',    '12.0',   'ERROR',    '10.0',    '20.0',     '9.0',    '16.0',
    '15.0',    '25.0',     '8.0',     '5.0',     '3.0',     '6.0',       nan,
 'UNKNOWN',     '2.0',     '1.0',     '7.5',     '4.5',     '1.5']
Length: 20, dtype: str

In [17]:
df.loc[df['Total Spent'].isin(['ERROR','UNKNOWN']),'Total Spent'] = np.nan

In [18]:
df['Total Spent'] = df['Total Spent'].astype(float)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: float64(3), str(5)
memory usage: 1005.0 KB

#### filling the null values of `Quantity` Column

In [20]:
mask = (df['Price Per Unit'].notna())&(df['Total Spent'].notna())
df.loc[df['Quantity'].isna() & mask]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
20,TXN_3522028,Smoothie,NaN,4.0,20.0,Cash,In-store,2023-04-04
55,TXN_5522862,Cookie,NaN,1.0,2.0,Credit Card,Takeaway,2023-03-19
57,TXN_2080895,Cake,NaN,3.0,3.0,Digital Wallet,In-store,2023-04-19
66,TXN_8501819,Juice,NaN,3.0,6.0,Cash,NaN,2023-03-30
117,TXN_2148617,Juice,NaN,3.0,9.0,Digital Wallet,UNKNOWN,2023-01-10
...,...,...,...,...,...,...,...,...
9932,TXN_8502079,Tea,NaN,1.5,3.0,Cash,NaN,2023-04-20
9935,TXN_9778251,Tea,NaN,1.5,6.0,NaN,Takeaway,2023-11-09
9944,TXN_7495283,Cake,NaN,3.0,15.0,Credit Card,Takeaway,2023-04-14
9957,TXN_6487003,Coffee,NaN,2.0,8.0,Credit Card,Takeaway,2023-11-15
9984,TXN_3142496,Smoothie,NaN,4.0,4.0,Cash,Takeaway,2023-07-27

In [21]:
df['Quantity'] = df['Quantity'].fillna(df['Total Spent'] / df['Price Per Unit'])

In [22]:
df['Quantity'].isna().sum()

np.int64(38)

In [23]:
df.loc[df['Quantity'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
236,TXN_8562645,Salad,NaN,5.0,NaN,NaN,In-store,2023-05-18
278,TXN_3229409,Juice,NaN,3.0,NaN,Cash,Takeaway,2023-04-15
629,TXN_9289174,Cake,NaN,NaN,12.0,Digital Wallet,In-store,2023-12-30
641,TXN_2962976,Juice,NaN,3.0,NaN,NaN,NaN,2023-03-17
738,TXN_8696094,Sandwich,NaN,4.0,NaN,NaN,Takeaway,2023-05-14
912,TXN_1575608,Sandwich,NaN,NaN,20.0,ERROR,Takeaway,2023-01-05
1008,TXN_7225428,Tea,NaN,NaN,3.0,Credit Card,Takeaway,2023-03-07
1436,TXN_7590801,Tea,NaN,NaN,6.0,Cash,Takeaway,ERROR
1482,TXN_3593060,Smoothie,NaN,NaN,16.0,Cash,NaN,2023-03-05
2330,TXN_3849488,Salad,NaN,NaN,5.0,NaN,In-store,2023-03-01
2796,TXN_9188692,Cake,NaN,3.0,NaN,Credit Card,NaN,2023-12-01
3203,TXN_4565754,Smoothie,NaN,4.0,NaN,Digital Wallet,Takeaway,2023-10-06
3224,TXN_6297232,Coffee,NaN,2.0,NaN,NaN,NaN,2023-04-07
3401,TXN_3251829,Tea,NaN,1.5,NaN,Digital Wallet,In-store,2023-07-25
3635,TXN_6177081,Cookie,NaN,NaN,1.0,Cash,ERROR,2023-07-26
3779,TXN_7376255,UNKNOWN,NaN,NaN,25.0,NaN,In-store,2023-05-27
4257,TXN_6470865,Coffee,NaN,2.0,NaN,Digital Wallet,Takeaway,2023-09-18
5639,TXN_6206792,Tea,NaN,NaN,6.0,Credit Card,NaN,2023-10-13
5841,TXN_5884081,Cookie,NaN,1.0,NaN,Digital Wallet,In-store,2023-07-05
5845,TXN_8388462,Smoothie,NaN,NaN,8.0,UNKNOWN,Takeaway,2023-08-19
6225,TXN_6859249,Cookie,NaN,NaN,2.0,NaN,UNKNOWN,NaN
6661,TXN_5308047,Cookie,NaN,NaN,1.0,Credit Card,NaN,2023-10-28
6674,TXN_3071092,Coffee,NaN,NaN,4.0,ERROR,NaN,2023-09-08
7029,TXN_4628338,Coffee,NaN,2.0,NaN,Cash,NaN,2023-12-25
7297,TXN_9944500,Smoothie,NaN,4.0,NaN,Cash,In-store,2023-01-03
7597,TXN_1082717,ERROR,NaN,NaN,9.0,Digital Wallet,In-store,2023-12-13
8021,TXN_2428781,Salad,NaN,5.0,NaN,NaN,In-store,2023-05-09
8443,TXN_2023651,Sandwich,NaN,4.0,NaN,Cash,In-store,2023-05-25
8465,TXN_9669616,Coffee,NaN,2.0,NaN,NaN,ERROR,2023-06-03
8479,TXN_1547245,Sandwich,NaN,4.0,NaN,NaN,Takeaway,2023-09-11
8574,TXN_2546684,Juice,NaN,3.0,NaN,Digital Wallet,Takeaway,2023-04-08
8669,TXN_7764304,Cake,NaN,NaN,3.0,Credit Card,Takeaway,2023-01-09
8732,TXN_4550558,Cookie,NaN,1.0,NaN,Credit Card,In-store,2023-08-04
8975,TXN_8077367,Tea,NaN,NaN,7.5,Credit Card,NaN,2023-02-27
9464,TXN_5744797,Cake,NaN,NaN,3.0,Cash,In-store,2023-12-20
9590,TXN_9924732,Sandwich,NaN,4.0,NaN,Credit Card,In-store,2023-01-18
9819,TXN_1208561,NaN,NaN,NaN,20.0,Credit Card,NaN,2023-08-19
9869,TXN_1975184,Coffee,NaN,2.0,NaN,Digital Wallet,NaN,2023-01-15

#### fill the `Price Per Unit` from item's median

In [24]:
df.groupby('Item')['Price Per Unit'].median() - df.groupby('Item')['Price Per Unit'].mean()

Item
Cake        0.000000
Coffee      0.000000
Cookie      0.000000
ERROR       0.055556
Juice       0.000000
Salad       0.000000
Sandwich    0.000000
Smoothie    0.000000
Tea         0.000000
UNKNOWN     0.119632
Name: Price Per Unit, dtype: float64

### There is a gap between the `median` and the `mean` for the `ERROR` and `UNKNOWN` values, so they will be converted to `NaN` in order to repair them

In [25]:
df.loc[df['Item'].isin(['ERROR','UNKNOWN']),'Item'] = np.nan

In [26]:
df.loc[df['Item'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
6,TXN_4433211,NaN,3.0,3.0,9.0,ERROR,Takeaway,2023-10-06
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28
14,TXN_8915701,NaN,2.0,1.5,3.0,NaN,In-store,2023-03-21
30,TXN_1736287,NaN,5.0,2.0,10.0,Digital Wallet,NaN,2023-06-02
31,TXN_8927252,NaN,2.0,1.0,NaN,Credit Card,ERROR,2023-11-06
...,...,...,...,...,...,...,...,...
9951,TXN_4122925,NaN,4.0,1.0,4.0,NaN,Takeaway,2023-10-20
9958,TXN_4125474,NaN,2.0,5.0,10.0,Credit Card,In-store,2023-08-02
9981,TXN_4583012,NaN,5.0,4.0,20.0,Digital Wallet,NaN,2023-02-27
9994,TXN_7851634,NaN,4.0,4.0,16.0,NaN,NaN,2023-01-08
9996,TXN_9659401,NaN,3.0,NaN,3.0,Digital Wallet,NaN,2023-06-02

#### filling the null values in `price per unit` column

In [27]:
df['Price Per Unit'] = df['Price Per Unit'].fillna(df.groupby('Item')['Price Per Unit'].transform('median'))

In [28]:
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Total Spent']/df['Quantity'])

In [29]:
df.loc[df['Price Per Unit'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
1761,TXN_3611851,NaN,4.0,NaN,NaN,Credit Card,NaN,2023-02-09
2289,TXN_7524977,NaN,4.0,NaN,NaN,ERROR,NaN,2023-12-09
3779,TXN_7376255,NaN,NaN,NaN,25.0,NaN,In-store,2023-05-27
4152,TXN_9646000,NaN,2.0,NaN,NaN,NaN,In-store,2023-12-14
7597,TXN_1082717,NaN,NaN,NaN,9.0,Digital Wallet,In-store,2023-12-13
9819,TXN_1208561,NaN,NaN,NaN,20.0,Credit Card,NaN,2023-08-19

In [30]:
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])
df['Total Spent'].isna().sum()

np.int64(23)

#### getting the unique values of every item that belongs to each price

In [31]:
df.groupby(['Price Per Unit','Item']).first()

                        Transaction ID  Quantity  Total Spent Payment Method  \
Price Per Unit Item
1.0            Cookie      TXN_4271903       4.0          4.0    Credit Card
1.5            Tea         TXN_6650263       2.0          3.0           Cash
2.0            Coffee      TXN_1961373       2.0          4.0    Credit Card
3.0            Cake        TXN_4977031       4.0         12.0           Cash
               Juice       TXN_6769710       2.0          6.0           Cash
4.0            Sandwich    TXN_6699534       4.0         16.0           Cash
               Smoothie    TXN_2602893       5.0         20.0    Credit Card
5.0            Salad       TXN_7034554       2.0         10.0        UNKNOWN

                         Location Transaction Date
Price Per Unit Item
1.0            Cookie    In-store       2023-07-19
1.5            Tea       Takeaway       2023-01-10
2.0            Coffee    Takeaway       2023-09-08
3.0            Cake      In-store       2023-05-16
               Juice     In-store       2023-02-24
4.0            Sandwich   UNKNOWN       2023-10-28
               Smoothie  In-store       2023-03-31
5.0            Salad      UNKNOWN       2023-04-27

In [32]:
df.loc[df['Price Per Unit'] == 1.0,'Item'] = 'Cookie'
df.loc[df['Price Per Unit'] == 1.5,'Item'] = 'Tea'
df.loc[df['Price Per Unit'] == 2.0,'Item'] = 'Coffee'
df.loc[df['Price Per Unit'] == 5.0,'Item'] = 'Salad'

In [33]:
df['Item'].isna().sum()

np.int64(480)

In [34]:
df.loc[df['Item'].isna(),'Price Per Unit'].unique()

array([ 3.,  4., nan])

In [35]:
df.loc[df['Item'].isna(),'Item_missing'] = True
df.loc[df['Item'].notna(),'Item_missing'] = False

In [36]:
df.loc[df['Item'].notna() & df['Total Spent'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Item_missing
236,TXN_8562645,Salad,NaN,5.0,NaN,NaN,In-store,2023-05-18,False
278,TXN_3229409,Juice,NaN,3.0,NaN,Cash,Takeaway,2023-04-15,False
641,TXN_2962976,Juice,NaN,3.0,NaN,NaN,NaN,2023-03-17,False
738,TXN_8696094,Sandwich,NaN,4.0,NaN,NaN,Takeaway,2023-05-14,False
2796,TXN_9188692,Cake,NaN,3.0,NaN,Credit Card,NaN,2023-12-01,False
3203,TXN_4565754,Smoothie,NaN,4.0,NaN,Digital Wallet,Takeaway,2023-10-06,False
3224,TXN_6297232,Coffee,NaN,2.0,NaN,NaN,NaN,2023-04-07,False
3401,TXN_3251829,Tea,NaN,1.5,NaN,Digital Wallet,In-store,2023-07-25,False
4257,TXN_6470865,Coffee,NaN,2.0,NaN,Digital Wallet,Takeaway,2023-09-18,False
5841,TXN_5884081,Cookie,NaN,1.0,NaN,Digital Wallet,In-store,2023-07-05,False
7029,TXN_4628338,Coffee,NaN,2.0,NaN,Cash,NaN,2023-12-25,False
7297,TXN_9944500,Smoothie,NaN,4.0,NaN,Cash,In-store,2023-01-03,False
8021,TXN_2428781,Salad,NaN,5.0,NaN,NaN,In-store,2023-05-09,False
8443,TXN_2023651,Sandwich,NaN,4.0,NaN,Cash,In-store,2023-05-25,False
8465,TXN_9669616,Coffee,NaN,2.0,NaN,NaN,ERROR,2023-06-03,False
8479,TXN_1547245,Sandwich,NaN,4.0,NaN,NaN,Takeaway,2023-09-11,False
8574,TXN_2546684,Juice,NaN,3.0,NaN,Digital Wallet,Takeaway,2023-04-08,False
8732,TXN_4550558,Cookie,NaN,1.0,NaN,Credit Card,In-store,2023-08-04,False
9590,TXN_9924732,Sandwich,NaN,4.0,NaN,Credit Card,In-store,2023-01-18,False
9869,TXN_1975184,Coffee,NaN,2.0,NaN,Digital Wallet,NaN,2023-01-15,False

In [37]:
df.loc[df['Item'].notna() & df['Quantity'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Item_missing
236,TXN_8562645,Salad,NaN,5.0,NaN,NaN,In-store,2023-05-18,False
278,TXN_3229409,Juice,NaN,3.0,NaN,Cash,Takeaway,2023-04-15,False
629,TXN_9289174,Cake,NaN,3.0,12.0,Digital Wallet,In-store,2023-12-30,False
641,TXN_2962976,Juice,NaN,3.0,NaN,NaN,NaN,2023-03-17,False
738,TXN_8696094,Sandwich,NaN,4.0,NaN,NaN,Takeaway,2023-05-14,False
912,TXN_1575608,Sandwich,NaN,4.0,20.0,ERROR,Takeaway,2023-01-05,False
1008,TXN_7225428,Tea,NaN,1.5,3.0,Credit Card,Takeaway,2023-03-07,False
1436,TXN_7590801,Tea,NaN,1.5,6.0,Cash,Takeaway,ERROR,False
1482,TXN_3593060,Smoothie,NaN,4.0,16.0,Cash,NaN,2023-03-05,False
2330,TXN_3849488,Salad,NaN,5.0,5.0,NaN,In-store,2023-03-01,False
2796,TXN_9188692,Cake,NaN,3.0,NaN,Credit Card,NaN,2023-12-01,False
3203,TXN_4565754,Smoothie,NaN,4.0,NaN,Digital Wallet,Takeaway,2023-10-06,False
3224,TXN_6297232,Coffee,NaN,2.0,NaN,NaN,NaN,2023-04-07,False
3401,TXN_3251829,Tea,NaN,1.5,NaN,Digital Wallet,In-store,2023-07-25,False
3635,TXN_6177081,Cookie,NaN,1.0,1.0,Cash,ERROR,2023-07-26,False
4257,TXN_6470865,Coffee,NaN,2.0,NaN,Digital Wallet,Takeaway,2023-09-18,False
5639,TXN_6206792,Tea,NaN,1.5,6.0,Credit Card,NaN,2023-10-13,False
5841,TXN_5884081,Cookie,NaN,1.0,NaN,Digital Wallet,In-store,2023-07-05,False
5845,TXN_8388462,Smoothie,NaN,4.0,8.0,UNKNOWN,Takeaway,2023-08-19,False
6225,TXN_6859249,Cookie,NaN,1.0,2.0,NaN,UNKNOWN,NaN,False
6661,TXN_5308047,Cookie,NaN,1.0,1.0,Credit Card,NaN,2023-10-28,False
6674,TXN_3071092,Coffee,NaN,2.0,4.0,ERROR,NaN,2023-09-08,False
7029,TXN_4628338,Coffee,NaN,2.0,NaN,Cash,NaN,2023-12-25,False
7297,TXN_9944500,Smoothie,NaN,4.0,NaN,Cash,In-store,2023-01-03,False
8021,TXN_2428781,Salad,NaN,5.0,NaN,NaN,In-store,2023-05-09,False
8443,TXN_2023651,Sandwich,NaN,4.0,NaN,Cash,In-store,2023-05-25,False
8465,TXN_9669616,Coffee,NaN,2.0,NaN,NaN,ERROR,2023-06-03,False
8479,TXN_1547245,Sandwich,NaN,4.0,NaN,NaN,Takeaway,2023-09-11,False
8574,TXN_2546684,Juice,NaN,3.0,NaN,Digital Wallet,Takeaway,2023-04-08,False
8669,TXN_7764304,Cake,NaN,3.0,3.0,Credit Card,Takeaway,2023-01-09,False
8732,TXN_4550558,Cookie,NaN,1.0,NaN,Credit Card,In-store,2023-08-04,False
8975,TXN_8077367,Tea,NaN,1.5,7.5,Credit Card,NaN,2023-02-27,False
9464,TXN_5744797,Cake,NaN,3.0,3.0,Cash,In-store,2023-12-20,False
9590,TXN_9924732,Sandwich,NaN,4.0,NaN,Credit Card,In-store,2023-01-18,False
9869,TXN_1975184,Coffee,NaN,2.0,NaN,Digital Wallet,NaN,2023-01-15,False

In [38]:
df['Quantity'] = df['Quantity'].fillna(df['Total Spent'] / df['Price Per Unit'])
df['Quantity'].isna().sum()

np.int64(23)

In [39]:
df['Payment Method'].unique()

<ArrowStringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str

In [40]:
df['Location'].unique()

<ArrowStringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

In [41]:
pd.crosstab(index= df['Payment Method'],columns=df['Location'])

Location        ERROR  In-store  Takeaway  UNKNOWN
Payment Method
Cash               87       702       664       74
Credit Card        82       681       669       84
Digital Wallet     78       695       744       71
ERROR              12        91        75       10
UNKNOWN             7        78        88       12

#### All the numbers are very close, so no decision can be made

In [42]:
#2023-05-25
invalid_date = len(df['Transaction Date']) - df['Transaction Date'].str.match(r'^\d{4}-\d{2}-\d{2}$').sum()

In [43]:
mask = df['Transaction Date'].str.match(r'^\d{4}-\d{2}-\d{2}$')
len(df[~mask]) - invalid_date

np.int64(0)

In [44]:
df.loc[~mask,'Transaction Date'].unique()

<ArrowStringArray>
['ERROR', nan, 'UNKNOWN']
Length: 3, dtype: str

In [45]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], format='%Y-%m-%d', errors='coerce')

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9520 non-null   str
 2   Quantity          9977 non-null   float64
 3   Price Per Unit    9994 non-null   float64
 4   Total Spent       9977 non-null   float64
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
 8   Item_missing      10000 non-null  object
dtypes: datetime64[us](1), float64(3), object(1), str(4)
memory usage: 985.6+ KB

In [47]:
df.loc[df['Payment Method'].isin(['ERROR','UNKNOWN'])|df['Payment Method'].isna(), 'Payment Method']  = 'unknown'

In [48]:
df.loc[df['Location'].isin(['ERROR','UNKNOWN'])|df['Location'].isna(), 'Location']  = 'unknown'

In [49]:
df.loc[df['Transaction Date'].isna(),'Date_missing'] = True
df.loc[df['Transaction Date'].notna(),'Date_missing'] = False

In [50]:
mask = df['Quantity'].isna() | df['Price Per Unit'].isna() | df['Total Spent'].isna()
df.loc[mask,'Numeric_missing'] = True
df.loc[~mask,'Numeric_missing'] = False

In [51]:
df['Item_missing'] = df['Item_missing'].astype(bool)
df['Date_missing'] = df['Date_missing'].astype(bool)
df['Numeric_missing'] = df['Numeric_missing'].astype(bool)

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9520 non-null   str
 2   Quantity          9977 non-null   float64
 3   Price Per Unit    9994 non-null   float64
 4   Total Spent       9977 non-null   float64
 5   Payment Method    10000 non-null  str
 6   Location          10000 non-null  str
 7   Transaction Date  9540 non-null   datetime64[us]
 8   Item_missing      10000 non-null  bool
 9   Date_missing      10000 non-null  bool
 10  Numeric_missing   10000 non-null  bool
dtypes: bool(3), datetime64[us](1), float64(3), str(4)
memory usage: 975.6 KB

In [53]:
df.to_csv('output.csv', index= False)